### ISSUE TITLE
Library instead/in addition to shim?

### ISSUE THREAD

**Issue by DerGuteWolf** [pwasem/ui5-shim-babel-polyfill#1]
For an addition to a live transpile middleware having this as a shim is great.

However for the build wouldn't it be better to have the files in a library, esp. for use in FLP apps, so the files are loaded only once and not for every app?

Also see the problems in https://github.com/pfefferf/ui5-nwabap-deployer/issues/16, when using this shim as instructed, the files are NOT in the virtual workspace and thus are eg not deployed by this nwabap deployer task.

**Comment by pwasem** [comment]
@DerGuteWolf it does not make sense to have these files in a legacy library.
One would have to maintain / copy to this library manually.
You would loose all benefits from `npm` and the _modern_ tooling.

You can try to run:
```sh
ui5 build --all
```
to include all project dependencies into the build process.

For details please see https://sap.github.io/ui5-tooling/pages/CLI/#build

Hope this helps

**Comment by DerGuteWolf** [comment]
@pwasem : I agree with you that I do not want to maintain this manually, so even a seperate library would need an automatic build.
Unfortunatly "ui5 build --all" does not help getting these files deployed to an onpremise system, cf. https://github.com/pfefferf/ui5-nwabap-deployer/issues/16 . Apparently these files from dependencies are copied to dist and are visible to ui5 serve but are not directly visible to a ui5 build extension.
